kind: pipeline
name: test
workspace:
  base: /go
  path: src/github.com/shipt/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - tag

steps:
  - name: lint gtoken
    image: golang:1.16
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION
      - cd cmd/gtoken
      - go build ./...
      - golangci-lint run
  - name: lint gtoken-webhook
    image: golang:1.16
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION
      - cd cmd/gtoken-webhook
      - go build ./...
      - golangci-lint run
  - name: test gtoken
    image: golang:1.16
    commands:
      - cd cmd/gtoken
      - go test --race -v ./...
  - name: test gtoken-webhook
    image: golang:1.16
    commands:
      - cd cmd/gtoken-webhook
      - go test --race -v ./...
  - name: docker-prod-push gtoken
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    settings:
      context: cmd/gtoken
      dockerfile: cmd/gtoken/Dockerfile
      repo: harbor.shipttech.com/production/${DRONE_REPO_NAME}
      tags:
        - latest
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
      build_args_from_env:
        - GITHUB_TOKEN
    when:
      event:
        include:
          - tag

  - name: docker-prod-push gtoken-webhook
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    settings:
      context: cmd/gtoken
      dockerfile: cmd/gtoken-webhook/Dockerfile
      repo: harbor.shipttech.com/production/${DRONE_REPO_NAME}
      tags:
        - latest
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
      build_args_from_env:
        - GITHUB_TOKEN
    when:
      event:
        include:
          - tag
