// Code generated by mockery v1.0.0. DO NOT EDIT.

package gcp

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceAccountInfo is an autogenerated mock type for the ServiceAccountInfo type
type MockServiceAccountInfo struct {
	mock.Mock
}

// GetEmail provides a mock function with given fields:
func (_m *MockServiceAccountInfo) GetEmail() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields: _a0
func (_m *MockServiceAccountInfo) GetID(_a0 context.Context) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
